### ISSUE TITLE
./run serve is deprecated

### ISSUE THREAD

**Issue by kushalmahajan** [mike-works/pwa-fundamentals#145]
What can be the alternative to running http2 if not by this command. I am totally stuck for lighthouse audit.
Also, mention of port 5000 after switching to http2 is unclear. Anything in codefile or config I can relate to ?

**Comment by mike-north** [comment]
You shouldn't have to use HTTP2 for anything anymore. Lighthouse is now built in to chrome, and runs fine on `http://localhost:3000` over HTTP 1.1

If you run into problems, please make sure to include
* Your chrome version
* OS version (if windows, be sure to indicate which terminal you're using -- `cmd.exe`, `powershell`, `git-bash`, `cygwin`, `Ubuntu via windows subsystem for linux`, etc...)
* Node version
* Any error messages that may be in the console where you ran `npm start`
* Any error messages in the JS console
* A screenshot (if it will clarify the problem)

Just to make sure everything still works, I ran the 

![screen shot 2018-08-12 at 4 40 32 pm](https://user-images.githubusercontent.com/558005/44007669-8062d67e-9e4e-11e8-80a8-9ba7938da3cd.png)

**Comment by kushalmahajan** [comment]
Yes, that's fine. Infact I ran several audits just afew hours before.

But I was unable the see that http2 protocol in network panel as you
demonstrated.

So I assume now from discussion that --http2 was just for running
lighthouse.

**Comment by mike-north** [comment]
> So I assume now from discussion that --http2 was just for running
lighthouse.

We used to need a seperate server to run lighthouse, due to limitations (now fixed) of `webpack-dev-server` being unable to redirect HTTP to HTTPs traffic. Lighthouse _used to_ hard fail in the absence of this redirect.

Removing http2 support from the pwa project reduced a significant amount of complexity. native HTTP/2 support was [very much in flux](https://medium.com/the-node-js-collection/node-js-can-http-2-push-b491894e1bb1) until just a few months ago, and this PWA project had been using a [small Go program that received the HTTP/2 requests, and made the equivalent HTTP/1.1 calls to node](https://github.com/GoogleChromeLabs/simplehttp2server).
