### ISSUE TITLE
[Windows] Can't even install

### ISSUE THREAD

**Issue by chnebx** [mike-works/pwa-fundamentals#47]
The support given for installing this is not helping
first: the tutorial mentions a file : server/cli/cli.js which doesn't exist ??? ( which branch should we choose in order to follow your tutorials properly ? some branches have a server/cli folder, some don't ? 

After installing all dependencies with Yarn, I installed the certificates ( thanks for mentioning to win 10 users they have to get openSSL in their path ?), everything finally went well, I then ran "npm run watch" and there's some error in js mentinoning there's no API and UI, at the end of the day I went to learn about service workers and I finally wasted my time with little to no support to install your project. So I'm stuck what do I do now ?

So could you please give some recommendation for windows 10 users ( like me ) to install your app with clear instructions, the ones you gave either on FEM or on your readme don't work, for instance why do I always stumble upon errors in javascript files preventing me to launch the app in any cases ?

**Comment by chnebx** [comment]
Git bash helped me fix the "npm run prepcerts" so good so far but for some reason I get this error everytime : conccurently --names "API,UI" -c "bgBlue,bgMagenta" npm run watch:api and npm run watch:ui"
It's so frustrating getting stuck at this stage when the tutorial looks so interesting :(

**Comment by ShadyXV** [comment]
I run npm run watch:api and npm run watch:api in separate terminals they both worked. I was following the tutorial. 
npm run build:prod 
After this everything failed to run successfully. It wont start up. 
I tried installing Bash for windows 10 i still get the same errors up as your post, as u are getting at this point.

**Comment by mike-north** [comment]
I'll add to instructions that
- [ ] OpenSSL is required for cert generation
- [ ] You MUST be running in a bash shell (I recommend installing the [linux subsystem for windows](https://msdn.microsoft.com/en-us/commandline/wsl/install-win10))

This

> conccurently --names "API,UI" -c "bgBlue,bgMagenta" npm run watch:api and npm run watch:ui"

Is a command, not an error message. Is there any other output that can help shed some light on this?

Just for you two, I have built up a windows 10 VM and ensured that everything on the master branch works as expected. 

<img width="1702" alt="screen shot 2017-12-05 at 3 19 15 pm" src="https://user-images.githubusercontent.com/558005/33636120-c3763cf6-d9cf-11e7-969f-dc48119c831d.png">

Unfortunately, it works properly, which means I'm not seeing the issues that you are. If you like, we can screenshare so I can see what you're running into. Please set up a 15m appointment with me [here](https://mike.works/meet).

I'm very much looking forward to getting some additional information from you, so that I can reproduce this problem and fix it!

**Comment by ShadyXV** [comment]
Wow, everything works properly on your machine. What i did was, get bash working in windows 10, install node, npm install and npm run watch (using cert generated by node on windows- will this cause problems?), get alot of errors(from nodemon and sqlite3), try sudo npm install, also figure out I need ruby and scss on Bash.
I am on a Bash shell in windows, node 8.9.1.
I was getting module not found error for nodemon and sqlite3 needed to be manually installed.
But doth packages worked after i sudo npm install nodemon sqlite3.But now i am stuck here.
![image](https://user-images.githubusercontent.com/11807140/33647372-f6e9e17a-da7c-11e7-9091-3530371d98a9.png)
I have also installed sass. But I get errors related to scss files.
![image](https://user-images.githubusercontent.com/11807140/33647563-d0e73828-da7d-11e7-9b26-0f997e03c828.png)

**Comment by ShadyXV** [comment]
I want to start fresh.I mean reinstall bash and begin again.
What after that. Can you go through it step by step, like even what Linux packages need to be installed for it to work properly.

**Comment by Ingeborg2** [comment]
I am facing the same issues when trying to set up the project (windows 10 / visual studio code).  How can I solve this.  I would like to be able to follow along when going through this course.
Thank you in advance.

**Comment by mike-north** [comment]
@Ingeborg2 are you using [linux subsystem for windows](https://msdn.microsoft.com/en-us/commandline/wsl/install-win10) or a partially-complete bash implementation like `git-bash`?

I would love to be of help here, and an error log would give me some information to go on

**Comment by mike-north** [comment]
@ShadyXV you may want to try commenting out this line

https://github.com/mike-works/pwa-fundamentals/blob/e42b66dbcd9c7d6ec33153b43a91a4bd4aa4a232/webpack/plugins.config.js#L70

and see if this is the only thing in your way. The consequence of doing this is that you'll end up with a seperate CSS file instead of it being automatically embedded into your index.html

**Comment by Ingeborg2** [comment]
Hi Mike,

Thanks for your answer.  I have tried again after commenting out line 70, but it still did not work.

I tried with git bash first and then I have installed linux subsystem for windows.  I am unfamiliar with this.  I just navigated in to my folder and tried to run
npm run watch, but I got this:
![picture1](https://user-images.githubusercontent.com/29341169/39702969-df9775d0-5206-11e8-9dd3-5e69436b6c9f.png)

When I try to run npm run watch in visual studio code, this is what I get:
![picture2](https://user-images.githubusercontent.com/29341169/39702990-eff24fae-5206-11e8-83fc-1ddd3a9e87d2.png)

When I run npm run watch:ui in visual studio code, it works.
![picture3](https://user-images.githubusercontent.com/29341169/39703000-f7c2739e-5206-11e8-9a6f-43e8fd2ea18c.png)
![picture4](https://user-images.githubusercontent.com/29341169/39703004-fb307f58-5206-11e8-91b1-c8aacec9af02.png)

If you would have any other suggestions, that would be much appreciated.

Best regards,

Ingeborg

**Comment by mike-north** [comment]
@Ingeborg2 Which version of node are you running? You can find out by running
```
node --version
```
You should be using something newer than 7.0

**Comment by Ingeborg2** [comment]
I am using version 8.11.1

![image](https://user-images.githubusercontent.com/29341169/39708280-121bc91a-5217-11e8-9151-a00e81987c92.png)

**Comment by Ingeborg2** [comment]
I think the problem is that I do not know what I need to do exactly with the windows linux subsystem.  I am not familiar with this system.  For example, when I try to see which node version I am using (node --version), I get a message that it is not installed.  Do I need to install everyting again in the WLS?  I will try and look into it myselft, but if you have any extra information on it, that would be helpful too.

**Comment by mike-north** [comment]
@Ingeborg2 can we schedule a time to screenshare? I'd love to investigate exactly what's going on with your system, and straighten you out

https://mike.works/meet

**Comment by hmassoumi** [comment]
I was having the same issues as everyone else on windows 10. I used Git Bash, CygWin as well as Linux Subsystem to no avail. The problem is that even if you are using a bash shell npm is configured to use the Window cmd. You need to configure npm to use any of your bash shells. In my case I set the config like so:

` npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"`

After exiting out of VS Code and then opening it up again, I ran the commands:

yarn prepcerts
yarn watch

Everything works without any issues, per the instructions in the README.

**Comment by Josh68** [comment]
Although this issue is marked as closed, the solution is extremely flaky. Trying to do with with WSL seems to fail because the certs are actually installed within my WSL user home while my browser is looking for certs in my Windows user home. Going to try copying and see if that works (or spawning a browser from within WSL) or going to Linux, but it would be nice if this could just work in Windows, natively.

**Comment by mike-north** [comment]
This thread has served as a mixed bag of several windows issues. Please open new tickets if these or other windows-related things need attention
